valuesFilePath: ./values.yml

resources:
  - name: src_repo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.var.gitProvider }}
      path: {{ .Values.var.path }}
      branches:
        include: {{ .Values.var.branches }}
  - name: java_mvn_docker_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.var.Artifactory }}
      buildName: {{ .Values.var.pipelineName }}
      buildNumber: ${run_number}

pipelines:
  - name: {{ .Values.var.pipelineName }}
    configuration:
      jfrogCliVersion: '2'    # optional
    steps:
    - name: mvn_build
      type: MvnBuild
      configuration:
        affinityGroup: java_mvn_docker
        inputResources:
          - name: src_repo
        mvnCommand: mvn clean install      # optional
        #sourceLocation:       <string>      # optional
        #resolverSnapshotRepo: <string>      # optional
        #resolverReleaseRepo:  <string>      # optional
        #deployerSnapshotRepo: <string>      # optional
        #deployerReleaseRepo:  <string>      # optional
        forceXrayScan: true      # optional
        failOnScan: false     # default true
        #autoPublishBuildInfo: <string>      # optional
        #configFileLocation:   <string>      # optional
        #configFileName:       <string>      # optional
        outputResources:
          - name: java_mvn_docker_build_info
        execution:
          onStart:
            - echo "Preparing for work..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"

    - name: mvn_test
      type: MvnBuild
      configuration: ##save test
        affinityGroup: java_mvn_docker
      ##set run name
      ##set run description
      ##task -- slack integration
        inputResources:
          - name: src_repo
          - name: java_mvn_docker_build_info
        mvnCommand: mvn test      # optional
        #sourceLocation:       <string>      # optional
        #resolverSnapshotRepo: <string>      # optional
        #resolverReleaseRepo:  <string>      # optional
        #deployerSnapshotRepo: <string>      # optional
        #deployerReleaseRepo:  <string>      # optional
        #forceXrayScan:        <string>      # optional
        #failOnScan:           <boolean>     # default true
        #autoPublishBuildInfo: <string>      # optional
        #configFileLocation:   <string>      # optional
        #configFileName:       <string>      # optional
        outputResources:
          - name: java_mvn_docker_build_info
        execution:
          onStart:
            - echo "Preparing for work..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"

    - name: docker_build
      type: DockerBuild
      configuration:
        inputResources:
          - name: src_repo
          - name: java_mvn_docker_build_info
        affinityGroup: java_mvn_docker
        integrations:
          - name: {{ .Values.var.artifactory }} 
        dockerFileLocation: .
        dockerFileName: Dockerfile
        dockerImageName: {{ .Values.var.imageName }}   # replace with your image path and name
        dockerImageTag: ${run_number}
        outputResources:
          - name: java_mvn_docker_build_info
        execution:
          onStart:
            - echo "Preparing for work..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          
    - name: docker_publish
      type: DockerPush
      configuration:
        inputResources:
          - name: src_repo
          - name: java_mvn_docker_build_info
        integrations:
          - name: {{ .Values.var.artifactory }} 
        affinityGroup: java_mvn_docker
        targetRepository: {{ .Values.var.repo }}        #  may be required. Must be a local repository. Virtual repositories are not supported.
        forceXrayScan: true        # default false
        failOnScan: true       # default true
        autoPublishBuildInfo: true       # default false
        outputResources:
          - name: java_mvn_docker_build_info
        execution:
          onStart:
            - echo "Preparing for work..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"