valuesFilePath: ./values.yml

resources:
  - name: src_repo_1_java_mvn_docker_repo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.var.gitProvider }}
      path: {{ .Values.var.path }}
      branches:
        include: {{ .Values.var.branches }}

pipelines:
  - name: build_and_upload
    steps:
      - name: build
        type: Bash
        configuration:
          # integrations:
          #   - name: artifactory
          inputResources:
            - name: src_repo_1_java_mvn_docker_repo
        execution:
          onExecute:
            # - mvn clean build
            # - jfrog config use artifactory
            # - jf rt u --flat=true ${res_src_repo_resourcePath}/target/*.jar repo-name/
            # - save_tests $res_src_repo_resourcePath/target/surefire-reports/
            - cd $res_src_repo_1_java_mvn_docker_repo_resourcePath
            - ls
            - docker buildx ls
            - docker buildx build . --attest type=provenance,mode=max
